import type { FilmographySnapshot } from '../../src/domain/snapshot'

export const snapshotFixture: FilmographySnapshot = {
  schemaVersion: 1,
  generatedAt: '2026-07-20T10:00:00Z',
  recommendationsGeneratedAt: '2026-07-20T09:30:00Z',
  watched: [
    {
      tmdbId: 129,
      mediaType: 'movie',
      title: 'Spirited Away',
      originalTitle: '千と千尋の神隠し',
      year: 2001,
      releaseDate: '2001-07-20',
      posterUrl: 'https://image.tmdb.org/t/p/w500/example.jpg',
      overview: 'A young girl enters a world ruled by spirits.',
      genres: ['Animation', 'Fantasy'],
      voteAverage: 8.5,
      popularity: 95.2,
      rating: 9.5,
      watchedAt: '2026-07-12',
      tags: ['dreamlike', 'coming-of-age'],
      review: 'A **tender** and uncanny journey.',
      sourceUrl: null,
      credits: {
        cast: [
          { tmdbId: 1001, name: 'Favorite Actor', profileUrl: null, role: 'Chihiro' },
          { tmdbId: 1010, name: 'Secondary Shared Actor', profileUrl: null, role: 'Friend' },
          { tmdbId: 1011, name: 'Supporting Actor A', profileUrl: null, role: 'Parent' },
        ],
        filmmaker: {
          tmdbId: 1002,
          name: 'Favorite Filmmaker',
          profileUrl: null,
          role: 'Director',
        },
      },
    },
    {
      tmdbId: 38,
      mediaType: 'movie',
      title: 'Eternal Sunshine of the Spotless Mind',
      originalTitle: null,
      year: 2004,
      releaseDate: '2004-03-19',
      posterUrl: null,
      overview: 'A relationship is erased from memory.',
      genres: ['Drama', 'Science Fiction'],
      voteAverage: 8.1,
      popularity: 63.4,
      rating: 8,
      watchedAt: '2026-05-03',
      tags: ['memory'],
      review: 'Form and feeling work together.',
      sourceUrl: null,
      credits: {
        cast: [
          { tmdbId: 1001, name: 'Favorite Actor', profileUrl: null, role: 'Joel' },
          { tmdbId: 1010, name: 'Secondary Shared Actor', profileUrl: null, role: 'Friend' },
          { tmdbId: 1012, name: 'Supporting Actor B', profileUrl: null, role: 'Clementine' },
        ],
        filmmaker: {
          tmdbId: 1002,
          name: 'Favorite Filmmaker',
          profileUrl: null,
          role: 'Director',
        },
      },
    },
  ],
  watchlist: [
    {
      tmdbId: 4935,
      mediaType: 'movie',
      title: 'Howl’s Moving Castle',
      originalTitle: 'ハウルの動く城',
      year: 2004,
      releaseDate: '2004-09-09',
      posterUrl: null,
      overview: 'A young woman is cursed by a witch.',
      genres: ['Animation', 'Fantasy'],
      voteAverage: 8.4,
      popularity: 85.4,
      interest: 9,
      notes: 'Save for a quiet Sunday.',
      tags: ['dreamlike'],
      dismissed: false,
    },
    {
      tmdbId: 10,
      mediaType: 'movie',
      title: 'Dismissed Film',
      originalTitle: null,
      year: 1990,
      releaseDate: null,
      posterUrl: null,
      overview: '',
      genres: [],
      voteAverage: null,
      popularity: null,
      interest: null,
      notes: '',
      tags: [],
      dismissed: true,
    },
  ],
  deterministicDiscoveries: [
    {
      tmdbId: 8392,
      mediaType: 'movie',
      title: 'My Neighbor Totoro',
      originalTitle: 'となりのトトロ',
      year: 1988,
      releaseDate: '1988-04-16',
      posterUrl: null,
      overview: 'Two sisters encounter gentle forest spirits.',
      genres: ['Animation', 'Fantasy'],
      voteAverage: 8.1,
      popularity: 79,
      predictedRating: 9,
      rationale: 'Your highly rated dreamlike animation suggests a strong match.',
      source: 'deterministic',
      generatedAt: '2026-07-20T09:30:00Z',
      provider: null,
      model: null,
    },
    {
      tmdbId: 10515,
      mediaType: 'movie',
      title: 'Castle in the Sky',
      originalTitle: '天空の城ラピュタ',
      year: 1986,
      releaseDate: '1986-08-02',
      posterUrl: null,
      overview: 'Two children search for a legendary floating castle.',
      genres: ['Animation', 'Adventure'],
      voteAverage: 8,
      popularity: 70,
      predictedRating: 8.8,
      rationale: 'Two children search for a legendary floating castle.',
      source: 'deterministic',
      generatedAt: '2026-07-20T09:30:00Z',
      provider: null,
      model: null,
    },
    {
      tmdbId: 81,
      mediaType: 'movie',
      title: 'Nausicaä of the Valley of the Wind',
      originalTitle: '風の谷のナウシカ',
      year: 1984,
      releaseDate: '1984-03-11',
      posterUrl: null,
      overview: 'A princess tries to prevent a war in a poisoned future.',
      genres: ['Animation', 'Fantasy'],
      voteAverage: 7.9,
      popularity: 68,
      predictedRating: 8.7,
      rationale: 'A princess tries to prevent a war in a poisoned future.',
      source: 'deterministic',
      generatedAt: '2026-07-20T09:30:00Z',
      provider: null,
      model: null,
    },
    {
      tmdbId: 12477,
      mediaType: 'movie',
      title: 'Grave of the Fireflies',
      originalTitle: '火垂るの墓',
      year: 1988,
      releaseDate: '1988-04-16',
      posterUrl: null,
      overview: 'Two siblings struggle to survive near the end of war.',
      genres: ['Animation', 'Drama'],
      voteAverage: 8.5,
      popularity: 65,
      predictedRating: 8.6,
      rationale: 'Two siblings struggle to survive near the end of war.',
      source: 'deterministic',
      generatedAt: '2026-07-20T09:30:00Z',
      provider: null,
      model: null,
    },
    {
      tmdbId: 128,
      mediaType: 'movie',
      title: 'Princess Mononoke',
      originalTitle: 'もののけ姫',
      year: 1997,
      releaseDate: '1997-07-12',
      posterUrl: null,
      overview: 'A cursed prince is drawn into a conflict between forest gods and humans.',
      genres: ['Animation', 'Fantasy'],
      voteAverage: 8.3,
      popularity: 90,
      predictedRating: 8.5,
      rationale: 'A cursed prince is drawn into a conflict between forest gods and humans.',
      source: 'deterministic',
      generatedAt: '2026-07-20T09:30:00Z',
      provider: null,
      model: null,
    },
    {
      tmdbId: 16859,
      mediaType: 'movie',
      title: 'Kiki’s Delivery Service',
      originalTitle: '魔女の宅急便',
      year: 1989,
      releaseDate: '1989-07-29',
      posterUrl: null,
      overview: 'A young witch starts an independent life in a seaside city.',
      genres: ['Animation', 'Family'],
      voteAverage: 7.8,
      popularity: 72,
      predictedRating: 8.4,
      rationale: 'A young witch starts an independent life in a seaside city.',
      source: 'deterministic',
      generatedAt: '2026-07-20T09:30:00Z',
      provider: null,
      model: null,
    },
    {
      tmdbId: 15370,
      mediaType: 'movie',
      title: 'Whisper of the Heart',
      originalTitle: '耳をすませば',
      year: 1995,
      releaseDate: '1995-07-15',
      posterUrl: null,
      overview: 'A young reader follows a cat and discovers an artist’s workshop.',
      genres: ['Animation', 'Drama'],
      voteAverage: 7.9,
      popularity: 55,
      predictedRating: 8.3,
      rationale: 'A young reader follows a cat and discovers an artist’s workshop.',
      source: 'deterministic',
      generatedAt: '2026-07-20T09:30:00Z',
      provider: null,
      model: null,
    },
  ],
  aiDiscoveries: [
    {
      tmdbId: 14160,
      mediaType: 'movie',
      title: 'Up',
      originalTitle: null,
      year: 2009,
      releaseDate: '2009-05-28',
      posterUrl: null,
      overview: 'An old man and a young scout travel by flying house.',
      genres: ['Animation', 'Adventure'],
      voteAverage: 8,
      popularity: 100,
      predictedRating: 8.5,
      rationale: 'Its balance of grief and wonder echoes themes in your reviews.',
      source: 'ai',
      generatedAt: '2026-07-20T09:30:00Z',
      provider: 'OpenAI-compatible',
      model: 'example-model',
    },
  ],
}
