import type { FilmographySnapshot } from '../../src/domain/snapshot'

export const snapshotFixture: FilmographySnapshot = {
  schemaVersion: 1,
  generatedAt: '2026-07-20T10:00:00Z',
  recommendationsGeneratedAt: '2026-07-20T09:30:00Z',
  watched: [
    {
      tmdbId: 129,
      title: 'Spirited Away',
      originalTitle: '千と千尋の神隠し',
      year: 2001,
      releaseDate: '2001-07-20',
      posterUrl: 'https://image.tmdb.org/t/p/w500/example.jpg',
      overview: 'A young girl enters a world ruled by spirits.',
      genres: ['Animation', 'Fantasy'],
      voteAverage: 8.5,
      popularity: 95.2,
      rating: 9.5,
      watchedAt: '2026-07-12',
      tags: ['dreamlike', 'coming-of-age'],
      review: 'A **tender** and uncanny journey.',
      sourceUrl: null,
    },
    {
      tmdbId: 38,
      title: 'Eternal Sunshine of the Spotless Mind',
      originalTitle: null,
      year: 2004,
      releaseDate: '2004-03-19',
      posterUrl: null,
      overview: 'A relationship is erased from memory.',
      genres: ['Drama', 'Science Fiction'],
      voteAverage: 8.1,
      popularity: 63.4,
      rating: 8,
      watchedAt: '2026-05-03',
      tags: ['memory'],
      review: 'Form and feeling work together.',
      sourceUrl: null,
    },
  ],
  watchlist: [
    {
      tmdbId: 4935,
      title: 'Howl’s Moving Castle',
      originalTitle: 'ハウルの動く城',
      year: 2004,
      releaseDate: '2004-09-09',
      posterUrl: null,
      overview: 'A young woman is cursed by a witch.',
      genres: ['Animation', 'Fantasy'],
      voteAverage: 8.4,
      popularity: 85.4,
      interest: 9,
      notes: 'Save for a quiet Sunday.',
      tags: ['dreamlike'],
      dismissed: false,
    },
    {
      tmdbId: 10,
      title: 'Dismissed Film',
      originalTitle: null,
      year: 1990,
      releaseDate: null,
      posterUrl: null,
      overview: '',
      genres: [],
      voteAverage: null,
      popularity: null,
      interest: null,
      notes: '',
      tags: [],
      dismissed: true,
    },
  ],
  deterministicDiscoveries: [
    {
      tmdbId: 8392,
      title: 'My Neighbor Totoro',
      originalTitle: 'となりのトトロ',
      year: 1988,
      releaseDate: '1988-04-16',
      posterUrl: null,
      overview: 'Two sisters encounter gentle forest spirits.',
      genres: ['Animation', 'Fantasy'],
      voteAverage: 8.1,
      popularity: 79,
      predictedRating: 9,
      rationale: 'Your highly rated dreamlike animation suggests a strong match.',
      source: 'deterministic',
      generatedAt: '2026-07-20T09:30:00Z',
      provider: null,
      model: null,
    },
  ],
  aiDiscoveries: [
    {
      tmdbId: 14160,
      title: 'Up',
      originalTitle: null,
      year: 2009,
      releaseDate: '2009-05-28',
      posterUrl: null,
      overview: 'An old man and a young scout travel by flying house.',
      genres: ['Animation', 'Adventure'],
      voteAverage: 8,
      popularity: 100,
      predictedRating: 8.5,
      rationale: 'Its balance of grief and wonder echoes themes in your reviews.',
      source: 'ai',
      generatedAt: '2026-07-20T09:30:00Z',
      provider: 'OpenAI-compatible',
      model: 'example-model',
    },
  ],
}
